name: Deploy React Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t everistben/react-app:latest \
          --build-arg VITE_NODE_ENV=production \
          --build-arg VITE_SERVER_BASE_URL=${{ secrets.VITE_SERVER_BASE_URL }} \
          .

      - name: Push Image to Docker Hub
        run: docker push everistben/react-app:latest


  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from Docker Hub
        run: docker pull everistben/react-app:latest

      - name: Remove old container
        run: docker rm -f reactjs-app-container || true

      - name: Run new container
        run: docker run -d -p 3000:80 --name reactjs-app-container everistben/react-app:latest